#######################################
##                                   ##
##  \                /    +-------   ##
##   \              /     |          ##
##    \            /      |          ##
##     \    /\    /       |   ---+   ##
##      \  /  \  /        |      |   ##
##       \/    \/         +------+   ##
##                                   ##
#######################################
#                                     #
#    WorldGuard for PocketMine-MP     #
#                                     #
#######################################
# Author: FoxWorn3365
#       | https://github.com/FoxWorn3365
# GitHub: https://github.com/FoxWorn3365/WorldGuard
# Relased under the AGPL License
# https://github.com/FoxWorn3365/WorldGuard/LICENSE
#######################################

enabled: true  # Whether the plugin is enabled
language: en   # Select the language

denied-message: Sorry but you cannot do this action!

custom-denied-message:
  block_place: Sorry but you cannot place blocks here!
